server:
  port: 8084

spring:
  application:
    name: ms-categoria

  datasource:
    url: jdbc:mysql://localhost:3307/db_categoria?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: root
    password:

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

  packages-to-scan: GameShelf.ms_categoria.controller
  paths-to-match: /api/**
