spring:
  application:
    name: ms-multa

  datasource:
    url: jdbc:mysql://localhost:3307/db_multa
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8087

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    enabled: true
    path: /v3/api-docs

  swagger-ui:
    enabled: true
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha

  packages-to-scan: GameShelf.ms_multa.controller
  paths-to-match: /api/**