spring:
  application:
    name: ms-prestamo

  datasource:
    url: jdbc:mysql://localhost:3307/db_prestamo
    username: root
    password: ""

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect

server:
  port: 8086

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
    tags-sorter: alpha  