# Nombre del microservicio en Eureka
spring.application.name=ms-usuario

# Puerto del microservicio de usuarios
server.port=8081

# Dirección del servidor Eureka
eureka.client.service-url.defaultZone=http://localhost:8761/eureka/